name = "tallgrass"
version = "0.0.4"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "Gleam wrapper for the PokeAPI."
licences = ["MIT"]
repository = { type = "github", user = "stevetoro", repo = "tallgrass" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

internal_modules = ["tallgrass/internal/*"]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_hackney = ">= 1.2.0 and < 2.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
decode = ">= 0.2.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
